package expenseTracker.domain;

public enum ExpenseType {
    UTILITIES, MORTGAGE, FUEL, CAR, HOME, COMMUNICATION, GROCERIES, CLEANING, ELECTRONICS, CLOTHING, PETS, SUBSCRIPTIONS, ENTERTAINMENT, EATING_OUT, EDUCATION, GIFTS, VACATION, HEALTH, OTHERS
}
